name: CI

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Test
        run: bun test

      - name: Build
        run: bun build src/cli.ts --target=bun --outdir /tmp/get-discover-build
